CC=/usr/lib/clang/ccc-analyzer -g -O0
LD=llvm-ld -native

parcle: utils.o main.o server.o http.o app.o config.o
	$(LD) main.o server.o http.o app.o config.o -o $@ -lpthread -llua -lm
	-rm $@.bc

.o:
	$(CC) -c -o $@.o $@.c

clean:
	-rm *.o parcle

# vim: ts=4 sw=4 st=4 sta tw=80 list
